"""add ai pipeline fields to products

Revision ID: 79564b7ff285
Revises: 5268b4e66da2
Create Date: 2026-08-23 23:21:50.109904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79564b7ff285'
down_revision: Union[str, Sequence[str], None] = '5268b4e66da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('suggested_price_min', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('suggested_price_max', sa.Integer(), nullable=True))
    op.alter_column('products', 'base_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'base_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('products', 'suggested_price_max')
    op.drop_column('products', 'suggested_price_min')
    op.drop_column('products', 'video_url')
    op.drop_column('products', 'owner_id')
    # ### end Alembic commands ###
